// <auto-generated />
using System;
using ForumTecnico.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumTecnico.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250609192036_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ForumTecnico.Models.Tema", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tem_descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tem_momento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usu_login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Temas");
                });
#pragma warning restore 612, 618
        }
    }
}
